# ===== PERFIL ACTIVO POR DEFECTO =====
spring.profiles.active=dev

# ===== SERVIDOR =====
server.port=8080

# ===== CONFIGURACIÓN DE LOGGING =====
logging.level.cl.Barberia=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG