# ===== PERFIL DE PRODUCCIÓN =====
server.port=8080

# ===== BASE DE DATOS POSTGRESQL =====
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/barberia_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# ===== SWAGGER DESACTIVADO (SEGURIDAD) =====
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

logging.level.cl.Barberia=INFO